import { Dish } from './types'

export const recipeLibrary: Dish[] = [
  // ==================== 面食类 ====================
  { id: 'n1', name: '番茄鸡蛋面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '快手'], emoji: '🍜' },
  { id: 'n2', name: '炸酱面', category: 'noodle', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🍝' },
  { id: 'n3', name: '红烧牛肉面', category: 'noodle', suitableWeather: ['rainy', 'cold'], cookingTime: 60, difficulty: 'medium', tags: ['硬菜', '暖身'], emoji: '🍜' },
  { id: 'n4', name: '阳春面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🍲' },
  { id: 'n5', name: '葱油拌面', category: 'noodle', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🍝' },
  { id: 'n6', name: '兰州拉面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🍜' },
  { id: 'n7', name: '担担面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 20, difficulty: 'easy', tags: ['重口', '下饭'], emoji: '🍜' },
  { id: 'n8', name: '油泼面', category: 'noodle', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['经典', '下饭'], emoji: '🍝' },
  { id: 'n9', name: '重庆小面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 20, difficulty: 'easy', tags: ['重口', '暖身'], emoji: '🍜' },
  { id: 'n10', name: '武汉热干面', category: 'noodle', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['经典', '快手'], emoji: '🍝' },
  { id: 'n11', name: '岐山臊子面', category: 'noodle', suitableWeather: ['rainy', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🍜' },
  { id: 'n12', name: '打卤面', category: 'noodle', suitableWeather: ['mild', 'cold'], cookingTime: 25, difficulty: 'easy', tags: ['家常', '暖身'], emoji: '🍝' },
  { id: 'n13', name: '河南烩面', category: 'noodle', suitableWeather: ['rainy', 'cold'], cookingTime: 40, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🍜' },
  { id: 'n14', name: '酸辣面', category: 'noodle', suitableWeather: ['rainy', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['开胃', '快手'], emoji: '🍜' },
  { id: 'n15', name: '鸡丝凉面', category: 'noodle', suitableWeather: ['hot', 'mild'], cookingTime: 20, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🍝' },
  { id: 'n16', name: '麻酱凉面', category: 'noodle', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🍝' },
  { id: 'n17', name: '肉丝炒面', category: 'noodle', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🍜' },
  { id: 'n18', name: '鸡蛋炒面', category: 'noodle', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🍝' },
  { id: 'n19', name: '豆角焖面', category: 'noodle', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['家常', '下饭'], emoji: '🍜' },
  { id: 'n20', name: '刀削面', category: 'noodle', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 25, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🍜' },
  { id: 'n21', name: '清汤面', category: 'noodle', suitableWeather: ['mild', 'rainy'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🍲' },
  { id: 'n22', name: '三鲜面', category: 'noodle', suitableWeather: ['mild', 'rainy'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🍜' },

  // ==================== 米饭类 ====================
  { id: 'r1', name: '红烧排骨', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 45, difficulty: 'medium', tags: ['硬菜', '下饭'], emoji: '🍖' },
  { id: 'r2', name: '番茄炒蛋', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['家常', '快手'], emoji: '🍅' },
  { id: 'r3', name: '宫保鸡丁', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 25, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🥜' },
  { id: 'r4', name: '回锅肉', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🥩' },
  { id: 'r5', name: '鱼香肉丝', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🥕' },
  { id: 'r6', name: '蒜蓉西兰花', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🥦' },
  { id: 'r7', name: '酸辣土豆丝', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🥔' },
  { id: 'r8', name: '糖醋里脊', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '下饭'], emoji: '🥩' },
  { id: 'r9', name: '麻婆豆腐', category: 'rice', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['重口', '下饭'], emoji: '🌶️' },
  { id: 'r10', name: '红烧茄子', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🍆' },
  { id: 'r11', name: '干煸豆角', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🫘' },
  { id: 'r12', name: '可乐鸡翅', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'easy', tags: ['硬菜', '下饭'], emoji: '🍗' },
  { id: 'r13', name: '京酱肉丝', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'medium', tags: ['经典', '下饭'], emoji: '🥩' },
  { id: 'r14', name: '锅包肉', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '下饭'], emoji: '🥩' },
  { id: 'r15', name: '水煮肉片', category: 'rice', suitableWeather: ['rainy', 'cold'], cookingTime: 25, difficulty: 'medium', tags: ['重口', '暖身'], emoji: '🌶️' },
  { id: 'r16', name: '孜然羊肉', category: 'rice', suitableWeather: ['cold', 'mild'], cookingTime: 20, difficulty: 'medium', tags: ['下饭', '暖身'], emoji: '🐑' },
  { id: 'r17', name: '韭菜炒鸡蛋', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['家常', '快手'], emoji: '🥬' },
  { id: 'r18', name: '芹菜炒肉', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🥬' },
  { id: 'r19', name: '蒜苔炒肉', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🥩' },
  { id: 'r20', name: '土豆烧牛肉', category: 'rice', suitableWeather: ['cold', 'rainy'], cookingTime: 60, difficulty: 'medium', tags: ['硬菜', '暖身'], emoji: '🥔' },
  { id: 'r21', name: '红烧带鱼', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '下饭'], emoji: '🐟' },
  { id: 'r22', name: '葱爆羊肉', category: 'rice', suitableWeather: ['cold', 'rainy'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '暖身'], emoji: '🐑' },
  { id: 'r23', name: '木须肉', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🥒' },
  { id: 'r24', name: '红烧鸡块', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 35, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🍗' },
  { id: 'r25', name: '蚝油生菜', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 5, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🥬' },
  { id: 'r26', name: '肉末茄子', category: 'rice', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🍆' },
  { id: 'r27', name: '辣子鸡', category: 'rice', suitableWeather: ['rainy', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['重口', '下饭'], emoji: '🌶️' },
  { id: 'r28', name: '糖醋排骨', category: 'rice', suitableWeather: ['mild', 'cold'], cookingTime: 40, difficulty: 'medium', tags: ['硬菜', '经典'], emoji: '🍖' },

  // ==================== 炖菜/煲类 ====================
  { id: 's1', name: '番茄牛腩煲', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 90, difficulty: 'hard', tags: ['硬菜', '暖身'], emoji: '🥘' },
  { id: 's2', name: '红烧肉', category: 'stew', suitableWeather: ['cold', 'mild'], cookingTime: 60, difficulty: 'medium', tags: ['硬菜', '下饭'], emoji: '🍖' },
  { id: 's3', name: '土豆炖鸡块', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 45, difficulty: 'easy', tags: ['家常', '暖身'], emoji: '🍗' },
  { id: 's4', name: '排骨炖豆角', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 50, difficulty: 'medium', tags: ['家常', '暖身'], emoji: '🥩' },
  { id: 's5', name: '萝卜炖牛腩', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 80, difficulty: 'medium', tags: ['暖身', '下饭'], emoji: '🥘' },
  { id: 's6', name: '小鸡炖蘑菇', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 60, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🍄' },
  { id: 's7', name: '酸菜炖粉条', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 40, difficulty: 'easy', tags: ['经典', '暖身'], emoji: '🥘' },
  { id: 's8', name: '冬瓜炖排骨', category: 'stew', suitableWeather: ['mild', 'hot'], cookingTime: 60, difficulty: 'medium', tags: ['清淡', '健康'], emoji: '🥣' },
  { id: 's9', name: '猪肉炖粉条', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 50, difficulty: 'easy', tags: ['经典', '暖身'], emoji: '🥘' },
  { id: 's10', name: '香菇炖鸡', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 60, difficulty: 'easy', tags: ['家常', '暖身'], emoji: '🍗' },
  { id: 's11', name: '羊肉炖萝卜', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 70, difficulty: 'medium', tags: ['暖身', '硬菜'], emoji: '🐑' },
  { id: 's12', name: '黄豆炖猪蹄', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 90, difficulty: 'medium', tags: ['硬菜', '滋补'], emoji: '🥩' },
  { id: 's13', name: '砂锅豆腐', category: 'stew', suitableWeather: ['rainy', 'cold'], cookingTime: 25, difficulty: 'easy', tags: ['清淡', '家常'], emoji: '🫘' },
  { id: 's14', name: '玉米排骨汤', category: 'stew', suitableWeather: ['mild', 'rainy'], cookingTime: 60, difficulty: 'easy', tags: ['清甜', '健康'], emoji: '🌽' },
  { id: 's15', name: '清炖狮子头', category: 'stew', suitableWeather: ['cold', 'mild'], cookingTime: 60, difficulty: 'hard', tags: ['硬菜', '经典'], emoji: '🦁' },
  { id: 's16', name: '红酒炖牛肉', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 120, difficulty: 'hard', tags: ['硬菜', '西式'], emoji: '🍷' },
  { id: 's17', name: '咖喱鸡肉', category: 'stew', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 35, difficulty: 'easy', tags: ['下饭', '快手'], emoji: '🍛' },
  { id: 's18', name: '山药炖排骨', category: 'stew', suitableWeather: ['cold', 'mild'], cookingTime: 60, difficulty: 'medium', tags: ['滋补', '健康'], emoji: '🥩' },
  { id: 's19', name: '莲藕排骨汤', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 70, difficulty: 'medium', tags: ['滋补', '经典'], emoji: '🥣' },
  { id: 's20', name: '豆腐炖鲫鱼', category: 'stew', suitableWeather: ['cold', 'rainy'], cookingTime: 40, difficulty: 'medium', tags: ['清淡', '滋补'], emoji: '🐟' },

  // ==================== 凉菜类 ====================
  { id: 'c1', name: '凉拌黄瓜', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🥒' },
  { id: 'c2', name: '凉拌木耳', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '健康'], emoji: '🍄' },
  { id: 'c3', name: '蒜泥白肉', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🥩' },
  { id: 'c4', name: '拍黄瓜', category: 'cold', suitableWeather: ['hot'], cookingTime: 5, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🥒' },
  { id: 'c5', name: '凉拌海带丝', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '健康'], emoji: '🥬' },
  { id: 'c6', name: '皮蛋豆腐', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清爽', '经典'], emoji: '🥚' },
  { id: 'c7', name: '口水鸡', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 40, difficulty: 'medium', tags: ['重口', '经典'], emoji: '🍗' },
  { id: 'c8', name: '夫妻肺片', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['重口', '经典'], emoji: '🌶️' },
  { id: 'c9', name: '凉拌金针菇', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🍄' },
  { id: 'c10', name: '老虎菜', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['开胃', '快手'], emoji: '🌶️' },
  { id: 'c11', name: '凉拌腐竹', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '下饭'], emoji: '🫘' },
  { id: 'c12', name: '糖拌西红柿', category: 'cold', suitableWeather: ['hot'], cookingTime: 5, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🍅' },
  { id: 'c13', name: '凉拌藕片', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '健康'], emoji: '🪷' },
  { id: 'c14', name: '蒜蓉粉丝蒸扇贝', category: 'cold', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'medium', tags: ['海鲜', '经典'], emoji: '🐚' },
  { id: 'c15', name: '老醋花生', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['下饭', '快手'], emoji: '🥜' },
  { id: 'c16', name: '凉拌菠菜', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '健康'], emoji: '🥬' },
  { id: 'c17', name: '凉拌豆芽', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🌱' },
  { id: 'c18', name: '红油肚丝', category: 'cold', suitableWeather: ['hot', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['重口', '下饭'], emoji: '🌶️' },

  // ==================== 汤类 ====================
  { id: 't1', name: '酸辣汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['开胃', '暖身'], emoji: '🥣' },
  { id: 't2', name: '紫菜蛋花汤', category: 'soup', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '清淡'], emoji: '🍲' },
  { id: 't3', name: '番茄蛋花汤', category: 'soup', suitableWeather: ['mild', 'rainy'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🍅' },
  { id: 't4', name: '冬瓜排骨汤', category: 'soup', suitableWeather: ['hot', 'mild'], cookingTime: 60, difficulty: 'medium', tags: ['清淡', '健康'], emoji: '🥣' },
  { id: 't5', name: '白菜豆腐汤', category: 'soup', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🥬' },
  { id: 't6', name: '菌菇汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['滋补', '清淡'], emoji: '🍄' },
  { id: 't7', name: '西红柿鸡蛋汤', category: 'soup', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🍅' },
  { id: 't8', name: '萝卜丝汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '暖身'], emoji: '🥕' },
  { id: 't9', name: '海带汤', category: 'soup', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'easy', tags: ['清淡', '健康'], emoji: '🥬' },
  { id: 't10', name: '榨菜肉丝汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '开胃'], emoji: '🥣' },
  { id: 't11', name: '玉米浓汤', category: 'soup', suitableWeather: ['cold', 'mild'], cookingTime: 25, difficulty: 'easy', tags: ['清甜', '西式'], emoji: '🌽' },
  { id: 't12', name: '三鲜汤', category: 'soup', suitableWeather: ['mild', 'rainy'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🍲' },
  { id: 't13', name: '西湖牛肉羹', category: 'soup', suitableWeather: ['cold', 'rainy'], cookingTime: 20, difficulty: 'medium', tags: ['经典', '暖身'], emoji: '🥣' },
  { id: 't14', name: '鲫鱼豆腐汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 40, difficulty: 'medium', tags: ['滋补', '经典'], emoji: '🐟' },
  { id: 't15', name: '疙瘩汤', category: 'soup', suitableWeather: ['rainy', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '暖身'], emoji: '🥣' },
  { id: 't16', name: '菠菜猪肝汤', category: 'soup', suitableWeather: ['cold', 'rainy'], cookingTime: 20, difficulty: 'medium', tags: ['滋补', '健康'], emoji: '🥬' },
  { id: 't17', name: '雪梨银耳汤', category: 'soup', suitableWeather: ['hot', 'mild'], cookingTime: 60, difficulty: 'easy', tags: ['清甜', '滋补'], emoji: '🍐' },
  { id: 't18', name: '南瓜汤', category: 'soup', suitableWeather: ['cold', 'rainy'], cookingTime: 25, difficulty: 'easy', tags: ['清甜', '暖身'], emoji: '🎃' },

  // ==================== 炒菜类 ====================
  { id: 'f1', name: '蒜蓉空心菜', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '清淡'], emoji: '🥬' },
  { id: 'f2', name: '青椒肉丝', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🫑' },
  { id: 'f3', name: '地三鲜', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 25, difficulty: 'medium', tags: ['家常', '下饭'], emoji: '🍆' },
  { id: 'f4', name: '干煸四季豆', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 20, difficulty: 'medium', tags: ['下饭', '经典'], emoji: '🫘' },
  { id: 'f5', name: '手撕包菜', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🥬' },
  { id: 'f6', name: '虎皮青椒', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🫑' },
  { id: 'f7', name: '蚝油杏鲍菇', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🍄' },
  { id: 'f8', name: '蒜蓉粉丝娃娃菜', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🥬' },
  { id: 'f9', name: '杭椒牛柳', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'medium', tags: ['下饭', '硬菜'], emoji: '🥩' },
  { id: 'f10', name: '西芹炒虾仁', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '健康'], emoji: '🍤' },
  { id: 'f11', name: '洋葱炒蛋', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['家常', '快手'], emoji: '🧅' },
  { id: 'f12', name: '苦瓜炒蛋', category: 'stirfry', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '去火'], emoji: '🥒' },
  { id: 'f13', name: '西兰花炒虾仁', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['清淡', '健康'], emoji: '🥦' },
  { id: 'f14', name: '荷兰豆炒腊肉', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['下饭', '家常'], emoji: '🫛' },
  { id: 'f15', name: '韭黄炒蛋', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🥚' },
  { id: 'f16', name: '尖椒炒肉', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['下饭', '家常'], emoji: '🫑' },
  { id: 'f17', name: '丝瓜炒蛋', category: 'stirfry', suitableWeather: ['hot', 'mild'], cookingTime: 10, difficulty: 'easy', tags: ['清淡', '快手'], emoji: '🥒' },
  { id: 'f18', name: '土豆片炒肉', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['家常', '下饭'], emoji: '🥔' },
  { id: 'f19', name: '藕片炒肉', category: 'stirfry', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '下饭'], emoji: '🪷' },
  { id: 'f20', name: '蒜苗回锅肉', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 25, difficulty: 'medium', tags: ['经典', '下饭'], emoji: '🥩' },
  { id: 'f21', name: '酸豆角肉末', category: 'stirfry', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['开胃', '下饭'], emoji: '🫛' },
  { id: 'f22', name: '小炒黄牛肉', category: 'stirfry', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'medium', tags: ['下饭', '硬菜'], emoji: '🥩' },

  // ==================== 小吃/快手 ====================
  { id: 'k1', name: '蛋炒饭', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🍚' },
  { id: 'k2', name: '煎饺', category: 'snack', suitableWeather: ['mild', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🥟' },
  { id: 'k3', name: '炒年糕', category: 'snack', suitableWeather: ['rainy', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['快手', '暖身'], emoji: '🍡' },
  { id: 'k4', name: '麻辣香锅', category: 'snack', suitableWeather: ['rainy', 'cold'], cookingTime: 30, difficulty: 'medium', tags: ['重口', '下饭'], emoji: '🌶️' },
  { id: 'k5', name: '煎饼果子', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'medium', tags: ['经典', '快手'], emoji: '🥞' },
  { id: 'k6', name: '肉夹馍', category: 'snack', suitableWeather: ['cold', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '顶饱'], emoji: '🥙' },
  { id: 'k7', name: '酸辣粉', category: 'snack', suitableWeather: ['rainy', 'cold'], cookingTime: 15, difficulty: 'easy', tags: ['重口', '暖身'], emoji: '🍜' },
  { id: 'k8', name: '麻辣烫', category: 'snack', suitableWeather: ['rainy', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['重口', '暖身'], emoji: '🥘' },
  { id: 'k9', name: '饺子', category: 'snack', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '顶饱'], emoji: '🥟' },
  { id: 'k10', name: '馄饨', category: 'snack', suitableWeather: ['rainy', 'cold', 'mild'], cookingTime: 20, difficulty: 'easy', tags: ['快手', '清淡'], emoji: '🥟' },
  { id: 'k11', name: '葱油饼', category: 'snack', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'medium', tags: ['经典', '快手'], emoji: '🫓' },
  { id: 'k12', name: '蛋饼', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '家常'], emoji: '🥚' },
  { id: 'k13', name: '炒河粉', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '下饭'], emoji: '🍝' },
  { id: 'k14', name: '螺蛳粉', category: 'snack', suitableWeather: ['rainy', 'cold'], cookingTime: 20, difficulty: 'easy', tags: ['重口', '网红'], emoji: '🍜' },
  { id: 'k15', name: '手抓饼', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '顶饱'], emoji: '🫓' },
  { id: 'k16', name: '烤冷面', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '经典'], emoji: '🥞' },
  { id: 'k17', name: '煲仔饭', category: 'snack', suitableWeather: ['cold', 'rainy'], cookingTime: 30, difficulty: 'medium', tags: ['经典', '硬菜'], emoji: '🍲' },
  { id: 'k18', name: '盖浇饭', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 15, difficulty: 'easy', tags: ['快手', '顶饱'], emoji: '🍛' },
  { id: 'k19', name: '三明治', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 5, difficulty: 'easy', tags: ['西式', '快手'], emoji: '🥪' },
  { id: 'k20', name: '炒方便面', category: 'snack', suitableWeather: ['mild', 'hot'], cookingTime: 10, difficulty: 'easy', tags: ['快手', '重口'], emoji: '🍝' },
  { id: 'k21', name: '炸鸡排', category: 'snack', suitableWeather: ['mild', 'cold'], cookingTime: 20, difficulty: 'medium', tags: ['硬菜', '下饭'], emoji: '🍗' },
  { id: 'k22', name: '凉皮', category: 'snack', suitableWeather: ['hot', 'mild'], cookingTime: 15, difficulty: 'easy', tags: ['清爽', '快手'], emoji: '🍜' },
]

export const categoryLabels: Record<string, string> = {
  noodle: '面食',
  rice: '米饭',
  stew: '炖菜',
  cold: '凉拌',
  soup: '汤类',
  stirfry: '炒菜',
  snack: '小吃',
}
